PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: trn.beethub.com.mx
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-trn-beethub-com-mx-p
    tlsacme: "true"
    urltemplate: '{{.Service}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
keycloak-db:
  existingSecret: keycloak-db
  mysqlUser: keycloak
  mysqlDatabase: keycloak
  persistence:
    storageClass: do-block-storage
keycloak-s:
  existingSecret: keycloak
  existingSecretKey: password
  persistence:
    deployPostgres: false
    dbVendor: mysql
    dbName: keycloak
    dbHost: keycloak-db
    dbPort: 3306
    existingSecret: keycloak-db
    existingSecretPasswordKey: mysql-password
    existingSecretUsernameKey: mysql-user
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    path: /
    hosts: 
    - keycloak.trn.beethub.com.mx
    tls: 
    - hosts: 
      - keycloak.trn.beethub.com.mx
      secretName: tls-trn-beethub-com-mx-p
